# Generated by Django 3.0.3 on 2020-09-23 07:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='about',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='mission',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
